apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft-secrets
  namespace: games
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vaultwarden-backend
    kind: ClusterSecretStore
  target:
    name: minecraft-secrets
    creationPolicy: Owner
  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: "70d64a7f-b041-4a44-a06a-e0668cf7bd01"
