apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: games
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - port: 25565
      targetPort: 25565
      name: mc
      protocol: TCP