apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fear-nightfall-data
  namespace: games
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 32Gi
