apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      containers:
        - name: comfyui
          image: yanwk/comfyui-boot:latest-rocm
          env:
            - name: HSA_OVERRIDE_GFX_VERSION
              value: "11.0.0"
            - name: CLI_ARGS
              value: "--listen 0.0.0.0 --port 8188"
          ports:
            - containerPort: 8188
              name: http
          volumeMounts:
            - name: data
              mountPath: /root/comfyui
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: comfyui-data
