apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vaultwarden-backend
    kind: ClusterSecretStore
  target:
    name: minecraft-secrets
    creationPolicy: Owner
  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: "PASTE_THE_VAULTWARDEN_ITEM_ID_HERE"