apiVersion: apps/v1
kind: Deployment
metadata:
  name: samba
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: samba
    spec:
      containers:
        - name: samba
          image: ghcr.io/servercontainers/samba:latest
          env:
            - name: SAMBA_GLOBAL_CONFIG_netbios_SPACE_name
              value: "HOMELAB"
            - name: SAMBA_GLOBAL_CONFIG_server_SPACE_string
              value: "homelab"
            - name: SAMBA_GLOBAL_CONFIG_workgroup
              value: "WORKGROUP"
            - name: SAMBA_GLOBAL_CONFIG_server_SPACE_min_SPACE_protocol
              value: "SMB2"
            - name: SAMBA_GLOBAL_CONFIG_disable_SPACE_netbios
              value: "no"
            - name: ACCOUNT_media
              value: "mediapw"
            - name: UID_media
              value: "1000"
            - name: SAMBA_VOLUME_CONFIG_media
              value: "[media]; path=/media; valid users = media; read only = no; browseable = yes; create mask = 0664; directory mask = 0775"
            - name: ACCOUNT_aslantishbek
              value: "8902Violet43$"
            - name: UID_aslantishbek
              value: "1000"
            - name: SAMBA_VOLUME_CONFIG_models
              value: "[models]; path=/models-host; valid users = aslantishbek; read only = no; browseable = yes; create mask = 0664; directory mask = 0775"
            - name: SAMBA_VOLUME_CONFIG_root
              value: "[root]; path=/host-root; valid users = aslantishbek; read only = no; browseable = yes; create mask = 0664; directory mask = 0775; force user = root"
          ports:
            - containerPort: 445
              name: smb
          volumeMounts:
            - name: media
              mountPath: /media
            - name: models
              mountPath: /models-host
            - name: rootfs
              mountPath: /host-root
          securityContext:
            capabilities:
              add: ["CAP_NET_BIND_SERVICE"]
      volumes:
        - name: media
          hostPath:
            path: /home/media
        - name: models
          hostPath:
            path: /home/media/comfyui-models
        - name: rootfs
          hostPath:
            path: /
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
