apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: samba-credentials
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden-backend
    kind: ClusterSecretStore
  target:
    name: samba-credentials
    creationPolicy: Owner
  data:
    - secretKey: aslantishbek-password
      remoteRef:
        key: samba-aslantishbek-password
