apiVersion: v1
kind: Service
metadata:
  name: samba
  namespace: apps
spec:
  type: NodePort
  selector:
    app: samba
  ports:
    - port: 445
      targetPort: 445
      nodePort: 30445
      name: smb
