apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - cert-manager
  - amd-gpu
  - external-secrets
  - external-secrets-store-sync.yaml
  - monitoring
  - apps-sync.yaml
