apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-backup-creds
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vaultwarden-backend
    kind: ClusterSecretStore
  target:
    name: vaultwarden-backup-creds
    creationPolicy: Owner
  data:
    - secretKey: restic-passphrase
      remoteRef:
        key: restic-passphrase
    - secretKey: aws-access-key-id
      remoteRef:
        key: aws-backup-access-key-id
    - secretKey: aws-secret-access-key
      remoteRef:
        key: aws-backup-secret-access-key
