apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3x-ui
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3x-ui
  template:
    metadata:
      labels:
        app: 3x-ui
    spec:
      containers:
        - name: 3x-ui
          image: ghcr.io/mhsanaei/3x-ui:latest@sha256:34c46ea6d838df981c4760bd1fe442413c2b99bbe4bb49dfa3d1bfb8a8a92496
          ports:
            - containerPort: 2053
              name: web
            - containerPort: 26789
              name: vpn-tcp
              protocol: TCP
            - containerPort: 26789
              name: vpn-udp
              protocol: UDP
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 2053
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: db
              mountPath: /etc/x-ui/
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: 3x-ui-db
