apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 3x-ui-db
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
