apiVersion: v1
kind: Service
metadata:
  name: x-ui
  namespace: apps
spec:
  type: LoadBalancer
  selector:
    app: 3x-ui
  ports:
    - name: web
      protocol: TCP
      port: 2053
      targetPort: 2053
