apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vaultwarden-backend
spec:
  provider:
    webhook:
      url: "http://bitwarden-proxy.external-secrets.svc.cluster.local:8087/object/item/{{ .remoteRef.key }}"
      result:
        jsonPath: "$.data.login.password"