apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-creds
  namespace: monitoring
stringData:
  # This is a temporary password. You should change it.
  # We can manage this with External Secrets later!
  admin-user: "admin"
  admin-password: "CHANGEME_grafana123"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  dependsOn:
    - name: loki-stack
      namespace: monitoring
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "58.2.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  values:
    # Grafana configuration
    grafana:
      admin:
        existingSecret: "grafana-admin-creds"
        userKey: "admin-user"
        passwordKey: "admin-password"
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - "grafana.a-tishbek.info"
        path: /
        pathType: Prefix
        tls:
          - secretName: grafana-tls
            hosts:
              - "grafana.a-tishbek.info"
      # Add Loki as a datasource
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-stack.monitoring.svc.cluster.local:3100
          access: proxy
          isDefault: false
          jsonData:
            maxLines: 1000
      persistence:
        enabled: true
        storageClassName: "local-path"
        size: 10Gi

    # Prometheus configuration
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        retention: 15d