apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "AUTO_CURSEFORGE"
            - name: VERSION
              value: "1.20.1"
            - name: CF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: minecraft-secrets
                  key: CF_API_KEY
            - name: CF_PAGE_URL
              value: "https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4"
            - name: REMOVE_OLD_MODS
              value: "TRUE"
            - name: FORCE_REDOWNLOAD
              value: "TRUE"
            - name: MEMORY
              value: "10G" # Recommended for BMC4 server with overhead
          ports:
            - containerPort: 25565
              name: mc
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-data