apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vaultwarden-backend
    kind: ClusterSecretStore
  target:
    name: minecraft-secrets
    creationPolicy: Owner
  data:
    - secretKey: CF_API_KEY
      remoteRef:
        key: "074ae7b4-6366-4d3f-810c-13e4fe35e942" # Use your actual Vaultwarden item ID!